import type { Metadata } from "next";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//esse metadata seria o head do html, o head no next é especial
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//este layout é obrigatorio
// é o esqueleto do site, aqui vom o html

type RootLayoutProps ={
  children: React.ReactNode
}
export default function RootLayout({children}:{children:React.ReactNode}) {
  return (
    <html lang="pt-br">
      <body >
        {children}
      </body>
    </html>
  );
}
